name: Client CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch: 

jobs:
  build_audit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: corepack enable
      - run: yarn install
      - run: yarn check
      - run: yarn lint
      - run: yarn prettier